"""initial schema

Revision ID: 1495ebe5dc18
Revises: 
Create Date: 2026-08-31 18:09:04.555074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1495ebe5dc18'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery_centers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('doctors',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoices',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('number', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'paid', name='invoice_status'), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('billing_company', sa.String(), nullable=True),
    sa.Column('billing_address', sa.String(), nullable=True),
    sa.Column('billing_vat', sa.String(), nullable=True),
    sa.Column('billing_email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_table('patients',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.Enum('female', 'male', 'other', name='patient_gender'), nullable=True),
    sa.Column('allergies', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('rating', sa.Numeric(precision=2, scale=1), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('admin', 'doctor', 'assistant', name='user_role'), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', name='user_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('cases',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('case_number', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('new', 'in_planning', 'awaiting_approval', 'approved', 'in_treatment', 'completed', 'on_hold', name='case_status'), nullable=False),
    sa.Column('priority', sa.Enum('low', 'normal', 'high', name='case_priority'), nullable=False),
    sa.Column('treatment_type', sa.Enum('aligners', 'braces', 'retainer', 'surgical', name='case_treatment_type'), nullable=False),
    sa.Column('chief_complaint', sa.Text(), nullable=True),
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_number')
    )
    op.create_table('orders',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('ref', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'finished', name='order_status'), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=True),
    sa.Column('doctor_id', sa.String(), nullable=True),
    sa.Column('delivery_center_id', sa.String(), nullable=True),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.Column('delivery_on', sa.DateTime(), nullable=True),
    sa.Column('chief_complain', sa.Text(), nullable=True),
    sa.Column('treat_both_arch', sa.Boolean(), nullable=False),
    sa.Column('treatment_plan_type', sa.Enum('full_arch', 'anterior_only', '4_4_only', 'no_6_7', name='order_treatment_plan_type'), nullable=True),
    sa.Column('dont_move', sa.Text(), nullable=True),
    sa.Column('ap_relationship', sa.Enum('maintain', 'canine_only', 'canine_molar', 'both', name='order_ap_relationship'), nullable=True),
    sa.Column('anteroposterior', sa.String(), nullable=True),
    sa.Column('elastics', sa.Text(), nullable=True),
    sa.Column('open_bite', sa.Enum('correct', 'maintain', 'improved', name='order_open_bite'), nullable=True),
    sa.Column('midline', sa.Enum('maintain', 'correct', name='order_midline'), nullable=True),
    sa.Column('ipr', sa.Text(), nullable=True),
    sa.Column('bite_ramps', sa.Text(), nullable=True),
    sa.Column('crossbite', sa.Enum('correct', 'maintain', 'anterior', 'posterior', name='order_crossbite'), nullable=True),
    sa.Column('spaces', sa.Enum('close_all', 'maintain', name='order_spaces'), nullable=True),
    sa.Column('special_instructions', sa.Text(), nullable=True),
    sa.Column('cbct_enabled', sa.Boolean(), nullable=False),
    sa.Column('want_manufacturing', sa.Boolean(), nullable=False),
    sa.Column('material', sa.Enum('taglus', 'zendura', 'none', name='order_material'), nullable=True),
    sa.ForeignKeyConstraint(['delivery_center_id'], ['delivery_centers.id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ref')
    )
    op.create_table('invoice_orders',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('invoice_id', sa.String(), nullable=False),
    sa.Column('order_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lab_orders',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('ref', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.Column('lab', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'in_production', 'shipped', 'delivered', 'revision_needed', name='lab_order_status'), nullable=False),
    sa.Column('ordered_at', sa.Date(), nullable=False),
    sa.Column('eta', sa.Date(), nullable=True),
    sa.Column('stages', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ref')
    )
    op.create_table('observations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('user_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('plan', sa.String(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scans',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('upper', 'lower', name='scan_type'), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('format', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('treatment_plans',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('issued', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('treatment_plans')
    op.drop_table('scans')
    op.drop_table('observations')
    op.drop_table('lab_orders')
    op.drop_table('invoice_orders')
    op.drop_table('orders')
    op.drop_table('cases')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('products')
    op.drop_table('patients')
    op.drop_table('invoices')
    op.drop_table('doctors')
    op.drop_table('delivery_centers')
    # ### end Alembic commands ###
